name: 'integration'

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  auth_workload_identity_federation:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    name: 'auth_workload_identity_federation'
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v2'
        with:
          node-version: '16.x'

      - name: 'npm build'
        run: 'npm ci && npm run build'

      - uses: 'google-github-actions/auth@main'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
          service_account: '${{ secrets.GET_SECRETMANAGER_SECRETS_SA_EMAIL }}'

      - id: 'secrets'
        name: 'secrets'
        uses: './'
        with:
          secrets: |-
            token:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_REF }}
            password:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_VERSION_REF }}

      - name: 'outputs'
        run: echo '${{ steps.secrets.outputs.token }}:${{ steps.secrets.outputs.password }}'

      - id: 'env_secrets'
        name: 'env_secrets'
        uses: './'
        with:
          env_secrets: |-
            token:GHA_KEY
            GHA_KEY

      - name: 'outputs'
        run: echo '${{ steps.env_secrets.outputs.token }}:${{ steps.env_secrets.outputs.GHA_KEY }}'
