name: 'unit'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

# Kill the workflow if the PR is updated with a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: 'unit'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline
        shell: bash

      - name: 'build'
        run: yarn build

      - name: 'lint'
        run: yarn lint

      - name: 'test'
        run: yarn test
